name: Playwright E2E Tests

on:
  push:
    branches: [ main, master, feat/* ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - run: npm install

    - run: npx playwright install --with-deps

    - run: |
        sudo rm -rf pgdata
        sudo rm -rf postgres-data

    - run: |
        echo "POSTGRES_USER=postgres" >> .env
        echo "POSTGRES_PASSWORD=your_secure_password" >> .env
        echo "POSTGRES_DB=postgres" >> .env
        echo "DB_USER=postgres" >> .env
        echo "DB_PASSWORD=your_secure_password" >> .env
        echo "DB_NAME=postgres" >> .env
        echo "DB_PORT=5432" >> .env
        echo "DB_HOST=db" >> .env

    - run: docker compose up -d --build --wait

    - run: npx playwright test

    - if: failure()
      run: |
        docker logs automation_pg_container
        docker ps -a

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30